# Generated by Django 5.1.2 on 2024-11-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignosVitales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia_cardiaca', models.IntegerField()),
                ('tension_arterial_sistolica', models.IntegerField()),
                ('tension_arterial_diastolica', models.IntegerField()),
                ('saturacion_oxigeno', models.IntegerField()),
                ('frecuencia_respiratoria', models.IntegerField()),
                ('temperatura', models.FloatField()),
                ('urgencia', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
