# Generated by Django 5.1.1 on 2024-11-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historia_clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
