# Generated by Django 5.1.1 on 2024-11-08 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('nombre_eps', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_paciente', models.CharField(max_length=100)),
                ('apellido_paciente', models.CharField(max_length=100)),
                ('tipo_identificacion', models.CharField(max_length=100)),
                ('numero_identificacion', models.BigIntegerField(default=0)),
                ('edad_paciente', models.IntegerField()),
                ('genero_paciente', models.CharField(max_length=10)),
                ('direccion_paciente', models.CharField(max_length=100)),
                ('telefono_paciente', models.CharField(max_length=20)),
                ('correo_paciente', models.EmailField(blank=True, max_length=254, null=True)),
                ('tipo_sangre', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='historia_clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_historia', models.CharField(max_length=70, unique=True)),
                ('fecha_ingreso', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('motivo_ingreso', models.CharField(max_length=500)),
                ('motivo_salida', models.CharField(blank=True, max_length=500, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admision.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='eps_paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activo', 'Usuario Activo'), ('inactivo', 'Usuario Inactivo'), ('bloqueado', 'Usuario Bloqueado')], default='activo', max_length=20)),
                ('eps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admision.eps')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admision.paciente')),
            ],
        ),
    ]
